# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

install:
  - Rscript -e "install.packages('dplyr')"
  - Rscript -e "install.packages('knitr')"
  - Rscript -e "install.packages('maps')"
  - Rscript -e "install.packages('readr')"
  - Rscript -e "install.packages('tidyr')"
  - Rscript -e "install.packages('graphics')"
  - Rscript -e "install.packages('testthat')"
  - Rscript -e "install.packages('rmarkdown')"


script:
  - CI=false run build

